name: Build RMK firmware
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install rmk-cli and cargo-make
        uses: cargo-bins/cargo-binstall@main
        run: cargo binstall cargo-make rmk-cli -y
      - name: Create firmware project
        uses: actions/checkout@v3
        working-directory: .
        run: rmk-cli create --keyboard-toml-path keyboard.toml --vial-json-path vial.json --target-dir rmk
      - name: Build firmware
        uses: actions/checkout@v3
        working-directory: ./rmk
        run: cargo make uf2 --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware_uf2
          path: rmk/*.uf2
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware_hex
          path: rmk/*.hex
