name: Build RMK firmware
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rmk-cli and cargo-make
        run: cargo install --force cargo-make rmk-cli
      - name: Create firmware project
        working-directory: .
        run: rmk-cli create --keyboard-toml-path keyboard.toml --vial-json-path vial.json --target-dir rmk
      - name: Build firmware
        working-directory: ./rmk
        run: cargo make uf2 --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: rmk/*.uf2
      
  # merge:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   name: Merge Output Artifacts
  #   steps:
  #     - name: Merge Artifacts
  #       uses: actions/upload-artifact/merge@v4
  #       with:
  #         name: ${{ inputs.archive_name }}
  #         pattern: artifact-*
  #         delete-merged: true