name: Build RMK firmware
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cargo-bins/cargo-binstall@main
      - name: Install rmkit and cargo-make
        run: cargo binstall cargo-make rmkit -y
      - uses: actions/checkout@v3
      - name: Install libssl
        run: apt-get install pkg-config libssl-dev
      - name: Create firmware project
        working-directory: .
        run: rmkit create --keyboard-toml-path keyboard.toml --vial-json-path vial.json --target-dir rmk
      - name: Build firmware
        working-directory: ./rmk
        run: cargo make uf2 --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware_uf2
          path: rmk/*.uf2
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware_hex
          path: rmk/*.hex
